### ISSUE TITLE
Evaluate Legacy-Code scripts

### ISSUE THREAD

**Issue by Madwonk** [UND-Robotic-Mining-Team/Master-Guide#1]
Consider the three files in legacy-code scripts folder, and use a tool such as kdiff3 to compare them to the default files included with the Jetson, or find comparable online versions. It's entirely possible these are just default files included with the Jetson that can be deleted but someone ought to read through them and make sure.
https://github.com/UND-Robotic-Mining-Team/legacy-code/tree/devel/System%20Scripts

**Comment by herndez2** [comment]
so it looks like the jetson_clock.sh and jetson_clock2.sh are the exact same files and they are installed on the host computer when the imaging and flash happen on the host computer. So these are just default files included with the setup of the jetson and jetpack.

https://tm3.ghost.io/2018/07/06/setting-up-the-nvidia-jetson-tx2/ ( this is a link of how the jetson gets setup)


the cmakefile is cross-platform build evironment that create libraries, executables,  and compile source code. Not sure if the cmakefile located in the scripts is relavant,  it looks as if this file is looking for what type of operating system is being used and bringing in the phoenix library?(not totally sure if someone can also go over this text file so we can close this ticket

**Comment by Madwonk** [comment]
@herndez2 Good comments, it looks like the cmake file is a duplicate of what's used to build RobotMain and start the robot- I would say just keep using it, but I've had terrible experiences with cmake between versions and if we're going to have to redo it (Phoenix API has had several updates since then) we may as well do it right (instead of just using a template).

 In other words, all 3 of these files can probably removed or just plain ignored since we won't be using them; feel free to close the ticket afterwards. (Also, assign it to yourself so you can take credit!)
